language: python
branches:
  only:
    - main
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
install:
  - pip install tox-travis
  - pip install coverage
  - pip install codecov
script:
  - tox
after_success:
  - codecov